language: php
dist: xenial

matrix:
    include:
        - php: 7.1
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.2
        - php: 7.2
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.3
        - php: 7.3
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.4snapshot
        - php: 7.4snapshot
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
#       - php: nightly
#       - php: nightly
#         env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    allow_failures:
        - php: 7.4snapshot
#       - php: nightly

before_script:
    - |
        if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then
          COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"
        fi;
    - travis_wait composer update --no-interaction $COMPOSER_FLAGS

script:
    - php vendor/bin/simple-phpunit